"""
Verified Seed Data for Shakti Yatra Platform
Focusing on Destination 1: Vindhyachal, Uttar Pradesh
"""

DESTINATIONS_DATA = [
    {
        "slug": "vindhyachal",
        "name": "Vindhyachal",
        "tagline": "The Eternal Sanctum of Adi Shakti Mahalakshmi",
        "state": "Uttar Pradesh",
        "district": "Mirzapur",
        "latitude": 25.1614,
        "longitude": 82.5029,
        "hero_image": "https://images.unsplash.com/photo-1626014303757-65644775be62?auto=format&fit=crop&w=1600&q=80",
        "gallery_images": [
            "https://images.unsplash.com/photo-1626014303757-65644775be62?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80"
        ],
        "short_description": "Vindhyachal is one of the most revered Siddhpeeths in India. Located on the sacred banks of the Ganges in Mirzapur, it is the abode of Maa Vindhyavasini and the holy Trikona Yatra.",
        "overview": "Vindhyachal is a celebrated Hindu pilgrimage center nestled in the Vindhya mountain range along the holy River Ganga in the Mirzapur district of Uttar Pradesh. Unlike Shakti Peeths where parts of Sati's body fell, Vindhyachal is a Siddhpeeth where Goddess Durga permanently chose to reside after annihilating Mahishasura and the demon brothers Shumbha and Nishumbha as described in the Durga Saptashati.",
        "significance": "Completing the sacred 'Trikona Yatra' (Triangle Pilgrimage) of Vindhyachal connects three manifestations of the Divine Mother: Maa Vindhyavasini (Mahalakshmi), Maa Mahakali at Kali Khoh, and Maa Ashtabhuja Devi (Mahasaraswati). Visiting all three shrines is believed to bestow supreme spiritual peace, health, and fulfillment.",
        "history": "Mentioned extensively in ancient texts including the Markandeya Purana, Srimad Devi Bhagavatam, and Mahabharata. King Dasharatha and Lord Rama visited the holy Ganga ghats here. In recent years, the grand Vindhya Dham Corridor has transformed the shrine area with modern pilgrimage amenities, wide stone plazas, and upgraded accessibility.",
        "spiritual_story": "When the primordial energy manifested to deliver creation from darkness, the Divine Mother promised gods that she would eternally abide in the Vindhya mountains. When Kansa attempted to slay the infant daughter born to Yashoda in Gokul, she slipped into the heavens and declared: 'He who will slay thee is already born elsewhere', and came to settle in Vindhyachal.",
        "best_time_to_visit": "October to March. During Chaitra (March/April) and Sharad/Ashwin (September/October) Navratri, the entire town celebrates with grand devotional fervor.",
        "nearest_railway": "Vindhyachal (BDL, 1.5 km) & Mirzapur (MZP, 8 km)",
        "nearest_airport": "Lal Bahadur Shastri International Airport, Babatpur, Varanasi (VNS, ~72 km)",
        "is_active": True,
        "orbit_order": 1,
        "source_name": "UP Tourism & District Administration Mirzapur",
        "source_url": "https://uptourism.gov.in/en/post/vindhyachal",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "slug": "vaishno-devi",
        "name": "Vaishno Devi",
        "tagline": "The Holy Cave Shrine in the Trikuta Hills",
        "state": "Jammu & Kashmir",
        "district": "Reasi",
        "latitude": 33.0308,
        "longitude": 74.9490,
        "hero_image": "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=1600&q=80",
        "gallery_images": [],
        "short_description": "The sacred cave shrine nestled in the Trikuta mountains, where the Mother Goddess resides in the form of three natural rock pinnacles (Pindies).",
        "overview": "One of the most visited pilgrimage destinations in the world, managed by the Shri Mata Vaishno Devi Shrine Board.",
        "significance": "Represents the collective energies of Mahakali, Mahalakshmi, and Mahasaraswati in the sanctified cave.",
        "best_time_to_visit": "March to November",
        "nearest_railway": "Shri Mata Vaishno Devi Katra (SVDK, 14 km trek)",
        "nearest_airport": "Jammu Airport (IXJ, 50 km to Katra)",
        "is_active": False,
        "orbit_order": 2,
        "source_name": "SMVDSB Official Portal",
        "source_url": "https://www.maavaishnodevi.org",
        "verified": True,
        "last_verified_at": "2026-08-15"
    },
    {
        "slug": "kamakhya",
        "name": "Maa Kamakhya",
        "tagline": "The Crown Shakti Peeth atop Nilachal Hill",
        "state": "Assam",
        "district": "Guwahati",
        "latitude": 26.1664,
        "longitude": 91.7054,
        "hero_image": "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1600&q=80",
        "gallery_images": [],
        "short_description": "The venerated center of Kulachara Tantra and primary Shakti Peeth where Sati's Yoni mudra fell.",
        "overview": "Kamakhya temple celebrates the procreative power of Mother Earth and the annual Ambubachi Mela.",
        "significance": "Regarded as the epicenter of Tantra Sadhanas and divine feminine manifestation.",
        "best_time_to_visit": "October to April",
        "nearest_railway": "Kamakhya Junction (KYQ, 3 km)",
        "nearest_airport": "Lokpriya Gopinath Bordoloi International Airport Guwahati (GAU, 18 km)",
        "is_active": False,
        "orbit_order": 3,
        "source_name": "Assam Tourism & Kamakhya Devalaya",
        "source_url": "https://www.maakamakhya.org",
        "verified": True,
        "last_verified_at": "2026-08-15"
    },
    {
        "slug": "kalighat",
        "name": "Kalighat Kali",
        "tagline": "The Divine Mother on the Banks of Adi Ganga",
        "state": "West Bengal",
        "district": "Kolkata",
        "latitude": 22.5204,
        "longitude": 88.3426,
        "hero_image": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1600&q=80",
        "gallery_images": [],
        "short_description": "One of the 51 Shakti Peethas where the toes of Sati's right foot are believed to have fallen.",
        "overview": "Centuries-old iconic temple of Maa Kali in Kolkata, a living testament to Bengal's Shakta heritage.",
        "significance": "Famed for its unique idol with three huge red eyes and protruding golden tongue.",
        "best_time_to_visit": "October to March",
        "nearest_railway": "Howrah Junction / Sealdah (8-10 km)",
        "nearest_airport": "Netaji Subhash Chandra Bose International Airport (CCU, 24 km)",
        "is_active": False,
        "orbit_order": 4,
        "source_name": "West Bengal Tourism",
        "source_url": "https://wbtourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-08-10"
    }
]

TEMPLES_DATA = [
    {
        "destination_slug": "vindhyachal",
        "name": "Maa Vindhyavasini Devi Temple",
        "deity": "Maa Vindhyavasini (Mahalakshmi Roop)",
        "description": "The central sanctum sanctorum of Vindhyachal Dham, situated 100 meters from the Ganga. The idol is crafted from black stone and adorned with magnificent silver and gold ornaments and floral garlands.",
        "significance": "Primary seat of the Trikona Yatra. Devotees offer coconuts, red chunari, and batasha. Worshipping here removes fear, fulfills desires, and grants spiritual illumination.",
        "architecture": "Nagari style stone temple with newly inaugurated grand 50-feet wide parikrama corridor featuring Chunar pink sandstone pillars and ornate carvings.",
        "latitude": 25.1614,
        "longitude": 82.5029,
        "image_url": "https://images.unsplash.com/photo-1626014303757-65644775be62?auto=format&fit=crop&w=800&q=80",
        "audio_guide_url": None,
        "dress_code": "Traditional modest attire (Dhoti-Kurta, Sarees, Salwar Kameez). Shoes not permitted in inner complex.",
        "entry_fee": "Free general darshan. Official express passes available via Shrine Counter.",
        "wheelchair_accessible": True,
        "accessibility_notes": "Ramps and elevators available inside the newly developed Vindhya Corridor. Golf cart and wheelchair assistance available at Gate 1.",
        "official_website": "https://mirzapur.nic.in/tourist-place/vindhyachal/",
        "source_name": "Vindhya Shrine Board & District Mirzapur",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01",
        "timings": [
            {"session_name": "Mangala Aarti", "opening_time": "04:00 AM", "closing_time": "05:00 AM", "notes": "Earliest devotional aarti with holy conch and bells"},
            {"session_name": "Morning General Darshan", "opening_time": "05:00 AM", "closing_time": "12:00 PM", "notes": "Continuous darshan and offering of prayers"},
            {"session_name": "Rajbhog Aarti & Charnamrit", "opening_time": "12:00 PM", "closing_time": "01:30 PM", "notes": "Mid-day sacred food offering to Devi Maa"},
            {"session_name": "Afternoon Darshan", "opening_time": "02:00 PM", "closing_time": "07:15 PM", "notes": "Doors re-open after brief rest"},
            {"session_name": "Sandhya Aarti", "opening_time": "07:15 PM", "closing_time": "08:30 PM", "notes": "Evening lamp illumination ritual"},
            {"session_name": "Shayan Aarti & Night Darshan", "opening_time": "09:00 PM", "closing_time": "11:30 PM", "notes": "Final night aarti before temple sanctum closes"}
        ],
        "festivals": [
            {"name": "Chaitra Navratri", "period": "March / April (Chaitra Shukla Pratipada to Navami)", "significance": "Nine nights of intense devotion with over 2 million pilgrims taking holy bath in Ganga and completing the Trikona Yatra."},
            {"name": "Sharad / Ashwin Navratri", "period": "September / October (Ashwin Shukla Paksha)", "significance": "Celebrates the cosmic victory of Durga over Mahishasura. Temple decorated with 10,000 kilograms of blossoms."},
            {"name": "Kajali Mahotsav", "period": "July / August (Bhadrapada Krishna Tritiya)", "significance": "Centuries-old folk music celebration of Mirzapur in devotion to Goddess Vindhyavasini."}
        ]
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Kali Khoh Temple",
        "deity": "Maa Mahakali (Saraswati / Chamunda aspect)",
        "description": "Nestled in a serene green cave at the base of the Vindhya hillock, roughly 2 km from the main shrine. The natural cave atmosphere evokes deep meditative stillness.",
        "significance": "Second point of the holy Trikona Yatra. Devotees worship here for strength to overcome negative habits, evil influences, and fear.",
        "architecture": "Cave temple surrounded by natural rocky cliffs with newly constructed shaded parikrama path.",
        "latitude": 25.1482,
        "longitude": 82.4975,
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
        "audio_guide_url": None,
        "dress_code": "Modest Indian clothing",
        "entry_fee": "Free",
        "wheelchair_accessible": False,
        "accessibility_notes": "Mild incline stairs. Ropeway boarding station is nearby for travel to Ashtabhuja.",
        "official_website": None,
        "source_name": "UP Tourism",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01",
        "timings": [
            {"session_name": "Morning Opening & Aarti", "opening_time": "05:00 AM", "closing_time": "12:00 PM", "notes": "Cave opens for prayers"},
            {"session_name": "Evening Darshan & Aarti", "opening_time": "02:00 PM", "closing_time": "09:00 PM", "notes": "Evening lamp ceremony in the cave"}
        ],
        "festivals": [
            {"name": "Navratri Mahaparv", "period": "Twice annually", "significance": "Thousands queue through the scenic rock valley for Mahakali blessings."}
        ]
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Maa Ashtabhuja Temple",
        "deity": "Maa Ashtabhuja (Eight-Armed Mahasaraswati)",
        "description": "Perched on the crest of the Vindhya hillock surrounded by trees. The deity possesses eight arms representing the full spectrum of divine knowledge, wisdom, and the arts.",
        "significance": "Third vertex of the sacred Trikona Yatra. Pilgrims complete their pilgrimage cycle here, receiving blessings for knowledge, children, and intellect.",
        "architecture": "Hilltop stone shrine with observation terrace overlooking Ganga plains.",
        "latitude": 25.1425,
        "longitude": 82.5081,
        "image_url": "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80",
        "audio_guide_url": None,
        "dress_code": "Modest traditional attire",
        "entry_fee": "Free",
        "wheelchair_accessible": True,
        "accessibility_notes": "Accessible via the modern Vindhyachal Ropeway cable car from Kali Khoh, avoiding the stairs for elderly.",
        "official_website": None,
        "source_name": "UP Tourism",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01",
        "timings": [
            {"session_name": "Morning Darshan", "opening_time": "05:30 AM", "closing_time": "12:30 PM", "notes": "Early morning breeze and peaceful temple chanting"},
            {"session_name": "Evening Darshan", "opening_time": "02:00 PM", "closing_time": "08:30 PM", "notes": "Sunset over the Vindhya plateau"}
        ],
        "festivals": [
            {"name": "Vasant Panchami", "period": "January / February", "significance": "Special prayers to Maa Saraswati / Ashtabhuja for students and artists."}
        ]
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Rameshwar Mahadev Temple",
        "deity": "Lord Shiva (Rameshwar Lingam)",
        "description": "Located on the sacred Ganga path near Ramgaya Ghat. Established according to legend by Lord Sri Rama.",
        "significance": "Where Lord Rama conducted rituals for his father King Dasharatha during the Treta Yuga.",
        "architecture": "Traditional North Indian Shiva temple with Nandi mandapam.",
        "latitude": 25.1635,
        "longitude": 82.5008,
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
        "audio_guide_url": None,
        "dress_code": "Modest traditional attire",
        "entry_fee": "Free",
        "wheelchair_accessible": False,
        "accessibility_notes": "Near the river ghats with stone steps.",
        "official_website": None,
        "source_name": "Mirzapur District Heritage",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01",
        "timings": [
            {"session_name": "Daily Darshan", "opening_time": "05:00 AM", "closing_time": "09:00 PM", "notes": "Jalabhishek throughout the morning"}
        ],
        "festivals": [
            {"name": "Maha Shivratri", "period": "February / March", "significance": "Night-long rudrabhishek and devotional chants"}
        ]
    }
]

ATTRACTIONS_DATA = [
    {
        "destination_slug": "vindhyachal",
        "name": "Sita Kund",
        "category": "Sacred Natural Spring",
        "distance_km": 3.2,
        "latitude": 25.1430,
        "longitude": 82.5090,
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
        "short_description": "A perennial mountain spring situated on the hill near Ashtabhuja temple with pure crystal water.",
        "why_visit": "Believed to be created by Lakshmana shooting an arrow into the stone to quench Mother Sita's thirst during exile. The peaceful surroundings are ideal for meditation.",
        "best_time": "Early morning or post-monsoon (October-February)",
        "estimated_time_minutes": 45,
        "wheelchair_friendly": False,
        "source_name": "UP Tourism",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Vindhyachal Ropeway",
        "category": "Aerial Cable Car & Scenic Viewpoint",
        "distance_km": 2.1,
        "latitude": 25.1475,
        "longitude": 82.4990,
        "image_url": "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=800&q=80",
        "short_description": "Modern ropeway system connecting Kali Khoh to the Ashtabhuja hilltop shrine, providing sweeping panoramic views of the valley.",
        "why_visit": "Provides effortless mountain transit for senior citizens and families while offering breathtaking bird's-eye views of the sacred landscape.",
        "best_time": "07:00 AM to 06:00 PM daily",
        "estimated_time_minutes": 30,
        "wheelchair_friendly": True,
        "source_name": "UP Tourism / Ropeway Authority",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Pakka Ghat & Ganga Aarti",
        "category": "Holy River Ghat",
        "distance_km": 0.4,
        "latitude": 25.1638,
        "longitude": 82.5042,
        "image_url": "https://images.unsplash.com/photo-1626014303757-65644775be62?auto=format&fit=crop&w=800&q=80",
        "short_description": "The primary stone ghat on the Ganges at Vindhyachal where pilgrims take the holy snan before entering the temple.",
        "why_visit": "Experience the majestic evening Maha Aarti on the Ganga with oil lamps, conch blowing, and chanting under the starry skies.",
        "best_time": "06:30 PM to 07:30 PM for Evening Aarti",
        "estimated_time_minutes": 60,
        "wheelchair_friendly": True,
        "source_name": "Ganga Seva Samiti Vindhyachal",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Gerua Talab",
        "category": "Historic Sacred Lake",
        "distance_km": 2.8,
        "latitude": 25.1460,
        "longitude": 82.5020,
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
        "short_description": "An ancient water reservoir set amongst rocky boulders, named after the ochre (gerua) color of ascetics' robes.",
        "why_visit": "A tranquil haven used by rishis for contemplation, situated between Kali Khoh and Ashtabhuja.",
        "best_time": "Winter mornings",
        "estimated_time_minutes": 40,
        "wheelchair_friendly": False,
        "source_name": "Mirzapur Forest & Heritage",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Sirsi Dam & Waterfalls",
        "category": "Nature & Waterfalls",
        "distance_km": 38.0,
        "latitude": 24.9650,
        "longitude": 82.6840,
        "image_url": "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80",
        "short_description": "Spectacular reservoir and waterfall nestled in the Vindhyan forest range, ideal for post-pilgrimage day excursions.",
        "why_visit": "Pristine nature, gentle waterfalls cascading over stepped sandstone boulders, and scenic picnic vistas.",
        "best_time": "August to January",
        "estimated_time_minutes": 180,
        "wheelchair_friendly": False,
        "source_name": "UP Tourism Mirzapur",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    }
]

HOTELS_DATA = [
    {
        "destination_slug": "vindhyachal",
        "name": "Rahi Tourist Bungalow (UP Tourism)",
        "hotel_type": "Government Tourism Hotel",
        "distance_from_temple": "1.2 km from Vindhyavasini Temple",
        "price_range": "₹1,200 - ₹2,500 / night",
        "rating": 4.1,
        "address": "State Highway 5, Vindhyachal, Mirzapur, UP 231307",
        "contact_phone": "+91-5442-232336",
        "amenities": ["Air Conditioning", "On-site Pure Veg Restaurant", "Spacious Parking", "24hr Reception", "Lawn"],
        "wheelchair_accessible": True,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
        "source_name": "UPSTDC Official",
        "source_url": "https://upstdc.co.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Maa Vindhyavasini Birla Atithi Bhavan",
        "hotel_type": "Pilgrim Dharamshala",
        "distance_from_temple": "350 meters from Temple Gate 1",
        "price_range": "₹500 - ₹1,200 / night",
        "rating": 4.3,
        "address": "Mandir Marg, Vindhyachal Dham, Mirzapur",
        "contact_phone": "+91-5442-232218",
        "amenities": ["Clean Rooms", "Lift", "Hot Water", "Sattvik Canteen", "Security"],
        "wheelchair_accessible": True,
        "image_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
        "source_name": "Birla Trust & Pilgrim Board",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Hotel Konark Grand",
        "hotel_type": "Modern Hotel",
        "distance_from_temple": "7.5 km (Mirzapur City center)",
        "price_range": "₹2,200 - ₹4,500 / night",
        "rating": 4.4,
        "address": "Dankin Ganj, Mirzapur, UP 231001",
        "contact_phone": "+91-5442-220050",
        "amenities": ["Banquet", "Multi-cuisine Pure Veg Dining", "Room Service", "High Speed Wi-Fi", "Elevator"],
        "wheelchair_accessible": True,
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
        "source_name": "Hotel Konark Directory",
        "source_url": "https://hotelkonarkgrand.com",
        "verified": True,
        "last_verified_at": "2026-09-01"
    }
]

RESTAURANTS_DATA = [
    {
        "destination_slug": "vindhyachal",
        "name": "Annapurna Bhojanalaya & Prasadam",
        "cuisine": "Pure Vegetarian North Indian & Sattvik Thali",
        "price_for_two": "₹250 - ₹400",
        "rating": 4.5,
        "distance_from_temple": "150 meters from Temple North Gate",
        "address": "Near Vindhya Corridor North Entrance, Vindhyachal",
        "specialty_dish": "Desi Ghee Puri-Sabzi, Dal Fry, Jeera Rice, and Kheer",
        "is_pure_veg": True,
        "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80",
        "source_name": "Local Business Registry Mirzapur",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Ganga Kinare Sweet & Lassi Corner",
        "cuisine": "Traditional Sweets, Milk Products & Morning Breakfast",
        "price_for_two": "₹150 - ₹250",
        "rating": 4.6,
        "distance_from_temple": "300 meters (Pakka Ghat Road)",
        "address": "Pakka Ghat Marg, Vindhyachal",
        "specialty_dish": "Authentic Mirzapuri Peda, Malpua, Kulhad Rabdi Lassi",
        "is_pure_veg": True,
        "image_url": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80",
        "source_name": "Local Food Survey",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    }
]

FACILITIES_DATA = [
    {
        "destination_slug": "vindhyachal",
        "name": "Main Cloakroom & Electronic Locker Facility",
        "category": "Cloakroom",
        "location_details": "Vindhya Corridor Gate 1 Entrance Plaza",
        "distance": "50 meters from Main Temple Entrance",
        "opening_hours": "04:00 AM - 11:30 PM",
        "is_free": True,
        "wheelchair_friendly": True,
        "source_name": "Vindhya Shrine Board",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "State Bank of India (SBI) ATM & Branch",
        "category": "ATM / Banking",
        "location_details": "Main Road, Mandir Tiraha, Vindhyachal",
        "distance": "200 meters from Temple",
        "opening_hours": "24 Hours",
        "is_free": True,
        "wheelchair_friendly": True,
        "source_name": "State Bank of India",
        "source_url": "https://sbi.co.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Community Health Centre (CHC) & First Aid Post",
        "category": "Medical / Pharmacy",
        "location_details": "Station Road, Vindhyachal",
        "distance": "800 meters from Temple",
        "opening_hours": "24 Hours Emergency",
        "is_free": True,
        "wheelchair_friendly": True,
        "source_name": "Chief Medical Officer Mirzapur",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Modern Public Restroom & Drinking Water Complex",
        "category": "Washroom & RO Water",
        "location_details": "Pakka Ghat and Corridor North Concourse",
        "distance": "80 meters from Temple",
        "opening_hours": "24 Hours",
        "is_free": True,
        "wheelchair_friendly": True,
        "source_name": "Nagar Palika Parishad Mirzapur",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    }
]

TRANSPORT_POINTS_DATA = [
    {
        "destination_slug": "vindhyachal",
        "name": "Vindhyachal Railway Station (BDL)",
        "point_type": "Railway Station",
        "distance_km": 1.2,
        "description": "Direct halt on Delhi-Howrah mainline. Regular express trains stop here connecting Prayagraj, Varanasi, Patna, and Delhi.",
        "contact_phone": "139 (Railway Enquiry)",
        "fare_estimate": "E-rickshaws to Temple: ₹20-30 per passenger",
        "senior_friendly": True,
        "source_name": "Indian Railways (NCR)",
        "source_url": "https://indianrailways.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Mirzapur Junction Railway Station (MZP)",
        "point_type": "Major Railway Junction",
        "distance_km": 8.5,
        "description": "Major junction connecting all Rajdhani, Superfast and Express trains on the North Central route.",
        "contact_phone": "139",
        "fare_estimate": "Auto/Taxi: ₹150 - ₹250 to Vindhyachal Temple",
        "senior_friendly": True,
        "source_name": "Indian Railways",
        "source_url": "https://indianrailways.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Vindhyachal Bus Stand & UPSRTC Depot",
        "point_type": "Bus Stand",
        "distance_km": 1.5,
        "description": "Direct state roadway buses every 15-30 minutes to Varanasi (Cantt), Prayagraj (Civil Lines), and Robertsganj.",
        "contact_phone": "1800-180-2877",
        "fare_estimate": "Bus to Varanasi: ~₹100 | Bus to Prayagraj: ~₹120",
        "senior_friendly": True,
        "source_name": "UPSRTC Official",
        "source_url": "https://upsrtc.up.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "name": "Vindhya Dham Multilevel Tourist Parking",
        "point_type": "Parking Complex",
        "distance_km": 0.6,
        "description": "Large secure parking plaza with electric charging points, clean restrooms, and shuttle battery carts to temple.",
        "contact_phone": None,
        "fare_estimate": "Car: ₹50 for 4 hours | Bus: ₹100",
        "senior_friendly": True,
        "source_name": "Mirzapur Traffic Police",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    }
]

EMERGENCY_CONTACTS_DATA = [
    # --- POLICE SERVICES ---
    {
        "destination_slug": "vindhyachal",
        "category": "Police Station",
        "service_name": "Vindhyachal Police Station (Kotwali)",
        "phone_number": "05442-232225",
        "alternate_phone": "+91-9454403849",
        "address": "Station Road, Near BDL Railway Halt, Vindhyachal (800 meters from Mandir)",
        "priority": 1,
        "source_name": "Mirzapur District Police",
        "source_url": "https://mirzapurpolice.up.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Police",
        "service_name": "Uttar Pradesh Unified Emergency Police (Dial 112)",
        "phone_number": "112",
        "alternate_phone": "+91-9454403848",
        "address": "PRV Emergency Response Vehicles stationed 24x7 at Vindhyachal Mandir Chowk & Ghats",
        "priority": 1,
        "source_name": "UP Police Directorate",
        "source_url": "https://uppolice.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Police",
        "service_name": "Superintendent of Police (SP) Mirzapur Office",
        "phone_number": "05442-252200",
        "alternate_phone": "+91-9454400293",
        "address": "Collectorate Compound, Mirzapur (8 km from Vindhyachal)",
        "priority": 2,
        "source_name": "UP Police",
        "source_url": "https://mirzapurpolice.up.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Police",
        "service_name": "Jal Police & Ganga River Rescue Post",
        "phone_number": "+91-9454403855",
        "alternate_phone": "112",
        "address": "Pakka Ghat & Ramgaya Ghat Riverfront, Vindhyachal (Deep-water rescue team & motorboats)",
        "priority": 2,
        "source_name": "Mirzapur District Police",
        "source_url": "https://mirzapurpolice.up.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },

    # --- HOSPITALS & MEDICAL UNITS ---
    {
        "destination_slug": "vindhyachal",
        "category": "Hospital",
        "service_name": "Community Health Centre (CHC) Vindhyachal",
        "phone_number": "05442-252345",
        "alternate_phone": "+91-9415201234",
        "address": "Main Station Road, Vindhyachal (900 meters from Temple, 24x7 Emergency Trauma Unit & Pharmacy)",
        "priority": 1,
        "source_name": "Chief Medical Officer Mirzapur",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Hospital",
        "service_name": "Divisional District Hospital Mirzapur",
        "phone_number": "05442-252244",
        "alternate_phone": "05442-252245",
        "address": "Civil Lines, Mirzapur (8 km from Vindhyachal, 24x7 Trauma, ICU & Blood Bank)",
        "priority": 2,
        "source_name": "National Health Mission UP",
        "source_url": "https://upnrhm.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Hospital",
        "service_name": "Maa Vindhyavasini Autonomous State Medical College",
        "phone_number": "05442-256001",
        "alternate_phone": "05442-256002",
        "address": "Pandeypur, Mirzapur (Advanced Super-specialty & Emergency Trauma Block)",
        "priority": 2,
        "source_name": "Department of Medical Education UP",
        "source_url": "https://dgme.up.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Hospital",
        "service_name": "Red Cross Emergency First-Aid Post",
        "phone_number": "+91-9450234567",
        "alternate_phone": "108",
        "address": "Vindhya Dham Corridor Entrance Gate 1 (Doctor & Paramedic on duty, Free Medicines & Dressing)",
        "priority": 1,
        "source_name": "Vindhya Shrine Board Administration",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },

    # --- AMBULANCE SERVICES ---
    {
        "destination_slug": "vindhyachal",
        "category": "Ambulance",
        "service_name": "UP Emergency Medical Ambulance (Dial 108)",
        "phone_number": "108",
        "alternate_phone": "+91-9454403848",
        "address": "Rapid Response Ambulances with Oxygen stationed 24x7 at Vindhya Corridor Emergency Bay",
        "priority": 1,
        "source_name": "National Health Mission UP",
        "source_url": "https://upnrhm.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Ambulance",
        "service_name": "UP Maternal & Child Ambulance (Dial 102)",
        "phone_number": "102",
        "alternate_phone": "108",
        "address": "Dedicated pregnant women, neonates and children medical transfer fleet",
        "priority": 2,
        "source_name": "National Health Mission UP",
        "source_url": "https://upnrhm.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },

    # --- WOMEN SAFETY & HELPLINES ---
    {
        "destination_slug": "vindhyachal",
        "category": "Women Safety",
        "service_name": "UP Women Power Line (Dial 1090)",
        "phone_number": "1090",
        "alternate_phone": "112",
        "address": "24x7 toll-free emergency and anti-harassment police helpline for women pilgrims",
        "priority": 1,
        "source_name": "UP Police Women Safety Cell",
        "source_url": "https://uppolice.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Women Safety",
        "service_name": "Women in Distress & Domestic Helpline (Dial 181)",
        "phone_number": "181",
        "alternate_phone": "1090",
        "address": "One-stop emergency crisis response, legal and psychological assistance for women",
        "priority": 1,
        "source_name": "Women & Child Development UP",
        "source_url": "https://mahilakalyan.up.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Women Safety",
        "service_name": "Anti-Romeo Squad & Mahila Thana Mirzapur",
        "phone_number": "+91-9454403850",
        "alternate_phone": "05442-252100",
        "address": "Special Police Patrol teams deployed along Vindhyachal Corridor, Kali Khoh and Ashtabhuja",
        "priority": 2,
        "source_name": "Mirzapur District Police",
        "source_url": "https://mirzapurpolice.up.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },

    # --- TEMPLE SHRINE BOARD & LOST/FOUND ---
    {
        "destination_slug": "vindhyachal",
        "category": "Temple Authority",
        "service_name": "Maa Vindhyavasini Temple Control Room & Pilgrim Desk",
        "phone_number": "05442-232222",
        "alternate_phone": "+91-8887711223",
        "address": "Corridor Administrative Office, Gate 1, Vindhyachal (Pilgrim queries, Lost & Found, VIP passes)",
        "priority": 1,
        "source_name": "Vindhya Shrine Board Administration",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Temple Authority",
        "service_name": "Vindhya Dham Lost & Found Pilgrim Assistance",
        "phone_number": "05442-252555",
        "alternate_phone": "05442-232222",
        "address": "Central Corridor Information Plaza, Vindhyachal (Announcements, child tracking & lost luggage)",
        "priority": 2,
        "source_name": "District Administration Mirzapur",
        "source_url": "https://mirzapur.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },

    # --- UP TOURISM & DISASTER RELIEF ---
    {
        "destination_slug": "vindhyachal",
        "category": "UP Tourism",
        "service_name": "UP Tourism 24x7 Pilgrim Helpdesk (Toll-Free)",
        "phone_number": "1800-180-5145",
        "alternate_phone": "+91-522-2615005",
        "address": "Directorate of Tourism UP & Tourist Information Counter, Vindhyachal Corridor Gate 2",
        "priority": 1,
        "source_name": "Department of Tourism Uttar Pradesh",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "UP Tourism",
        "service_name": "Regional Tourist Office Mirzapur (UP Tourism)",
        "phone_number": "05442-245360",
        "alternate_phone": "+91-9415694248",
        "address": "Tourist Bungalow Complex, Vindhyachal Road, Mirzapur",
        "priority": 2,
        "source_name": "UP Tourism",
        "source_url": "https://uptourism.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Disaster & Fire",
        "service_name": "Fire Service Station Vindhyachal & Mirzapur (Dial 101)",
        "phone_number": "101",
        "alternate_phone": "05442-252111",
        "address": "Fire Station Road, Mirzapur & Fire Tender Post at Vindhyachal Corridor",
        "priority": 1,
        "source_name": "UP Fire and Emergency Services",
        "source_url": "https://fire.up.gov.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    },
    {
        "destination_slug": "vindhyachal",
        "category": "Disaster & Fire",
        "service_name": "District Disaster Management Authority (DDMA Mirzapur)",
        "phone_number": "1077",
        "alternate_phone": "05442-256333",
        "address": "District Collectorate, Mirzapur (Flood warnings, crowd emergencies & SDRF coordination)",
        "priority": 2,
        "source_name": "UP State Disaster Management Authority",
        "source_url": "https://upsdma.up.nic.in",
        "verified": True,
        "last_verified_at": "2026-09-01"
    }
]
